### ISSUE TITLE
Units conversion problems main branch

### ISSUE THREAD

**Issue by lafourcadep** [Collab4exaNBody/exaNBody#52]
The units conversion for "mol" leads to wrong internal units apparently. It looks like replacing "g/mol" by "Da" and replacing 1/mol by "Da/g" remove the problems. Observed on molecular system in FF parameters and species using exastamp.

**Comment by carrardt** [comment]
particle to SI amount unit (mol) conversion factor was wrong. it has been corrected to 1.0e-23 / 6.02214076
